var Name = "Sagar Chopne";
var School = "MBES";
var Grade = "A";
var Section = "B";
var Roll_No = "22";
var Marks_English = "100";
var Marks_Hindi = "100";
var Marks_Marathi = "100";
console.log("------------------Report Card-----------------");
console.log("Name----->" + "            " + Name);
console.log("School----->" + "          " + School);
console.log("Grade----->" + "           " + Grade);
console.log("Section----->" + "         " + Section);
console.log("Roll_No----->" + "         " + Roll_No);
console.log("*********************Marks******************");
console.log("Marks_English----->" +  '\n' + Marks_English);
console.log("Marks_Hindi----->" +  '\n'   + Marks_Hindi);
console.log("Marks_Marathi----->" +  '\n' + Marks_Marathi);
console.log("------------------End-----------------");